{{- if .Values.extSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "base-service.fullname" . }}
spec:
  refreshInterval: {{ .Values.extSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.extSecret.secretStoreName }}
    kind: {{ .Values.extSecret.secretStoreKind }}
  target:
    name: {{ include "base-service.fullname" . }}
  dataFrom:
  - extract:
      key: {{ .Values.extSecret.dataKey }}
      property: {{ .Values.extSecret.dataProperty }}
{{- end }}
