apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "base-service.fullname" . }}
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "base-service.selectorLabels" . | nindent 6 }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
